# Welcome to Jekyll!

title: A whole new robotic world
description: A fun blog about developers, tech, llm machines, etc...
domain: ""
url: ""
baseurl: ""
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

author: User 70f5cba9-32ff-4a55-933d-8d48deea0c0b

# Serving
port: 4000
host: 0.0.0.0
