# Welcome to Jekyll!

title: A whole new robotic world  
description: A fun blog about developers, tech, llm machines, etc...
domain: ""
url: "https://roboticworldx.github.io/"
baseurl: ""
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: RoboticWorldX

twitter:
  username: RoboticWorldX
  card: summary
social:
  name: RoboticWorldX
  links:
    - https://twitter.com/RoboticWorldX
    - https://github.com/RoboticWorldX


# Serving
port: 4000
host: 0.0.0.0
