# Welcome to Jekyll!

title: "A whole new robotic world"  
description: "A fun blog about developers, tech, llm machines, etc..."
url: "https://roboticworldx.github.io"
baseurl: ""
domain: "https://roboticworldx.github.io"
author: "RoboticWorldX"

# Social settings
twitter:
  username: "RoboticWorldX"
  card: "summary"
social:
  name: "RoboticWorldX"
  links:
    - "https://twitter.com/RoboticWorldX"
    - "https://github.com/RoboticWorldX"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Serving
port: 4000
host: 0.0.0.0
